version: '2.0'

services:

   kafka_connect_splunk:

      image: "${DOCKER_REPO}/${CONTAINER_NAME}"
      container_name: "${CONTAINER_NAME}"
      hostname: "${HOSTNAME}"
      ports:
         - "${LISTEN_IP}:8083:8083"

      volumes:
        - ./mount/config:/opt/splunk-kafka-connect/config

