version: '2.0'

services:

   kafka_connect_splunk:

      image: "${DOCKER_REPO}/${CONTAINER_NAME}"
      container_name: "${CONTAINER_NAME}"
      hostname: "${HOSTNAME}"
      ports:
         - "8090:8083"

      volumes:
        - /data/etc/kafka-connect-splunk:/opt/splunk-kafka-connect/config

